version: '2'

services:
  service2_go_db:
    image: mysql:5.7
    volumes:
      - "./dckr_mysql:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: service2_go
      MYSQL_DATABASE: service2_go
      MYSQL_USER: service2_go
      MYSQL_PASSWORD: service2_go
    networks:
      - service2_go_net

  service2_go:
    image: ctf01d-game-simulation/service2_go:latest
    depends_on:
      - service2_go_db
    environment:
      SERVICE2_GO_MYSQL_HOST: service2_go_db
      SERVICE2_GO_MYSQL_DBNAME: service2_go
      SERVICE2_GO_MYSQL_USER: service2_go
      SERVICE2_GO_MYSQL_PASSWORD: service2_go
    ports:
      - "4102:4102"
    restart: always
    networks:
      - service2_go_net

networks:
  service2_go_net:
    driver: bridge
        